### ISSUE TITLE
128 servers is extremely little

### ISSUE THREAD

**Issue by Cabbasca** [DAMcraft/ServerSeekerAPI-docs#1]
you should make the servers endpoint return as many servers as the players endpoint (1000)

**Comment by rewrite** [comment]
I'd say add a max_results option, if its not in the request, return 128 servers, if its specified it will return the max_results results and it can be 1000 max.

**Comment by lina-x64** [comment]
I think 128 is a lot already for people that use it normally, if you need a special plan for a website or something, just message me on discord lol (@damcraft.de)

I just want my database to be less stressed
